from typing import Callable, Protocol
from app.orchestrator.models import ContainerInfo, ContainerSpec, ImageInfo


class RuntimeProvider(Protocol):
    """Only this boundary depends on the container engine.

    Blocking methods run in the worker thread, never in a request event loop.
    Implementations must make removal idempotent and limit operations to owned resources.
    """

    def create_network(self, session_id: str) -> str: ...
    def delete_network(self, network_id: str) -> None: ...
    def create_container(self, spec: ContainerSpec) -> str: ...
    def start_container(self, container_id: str) -> None: ...
    def start_activity(self, container_id: str, session_id: str, generation: int, cancelled: Callable[[], bool] | None = None) -> None: ...
    def stop_activity(self, container_id: str) -> None: ...
    def stop_container(self, container_id: str) -> None: ...
    def delete_container(self, container_id: str) -> None: ...
    def inspect_container(self, container_id: str) -> ContainerInfo: ...
    def probe_target(self, kali_id: str, target_ip: str, target_port: int) -> bool: ...
    def image_exists(self, image: str) -> bool: ...
    def load_image(self, path: str) -> ImageInfo: ...
    def remove_image(self, image_id: str) -> None: ...
    def image_in_use(self, image_id: str) -> bool: ...
    def session_resources(self, session_id: str) -> tuple[list[str], list[str]]: ...
    def managed_session_ids(self) -> set[str]: ...
    def owns_container(self, container_id: str, session_id: str) -> bool: ...
    def disconnect_desktop(self, container_id: str) -> None: ...
